FROM alpine/ansible:latest

WORKDIR /ansible

COPY ansible/ .

ENTRYPOINT ["ansible-playbook", "playbook-deploy.yml"]
CMD ["-i", "environments/staging/inventory", "-e", "env=staging", "--ask-vault-pass"]