---

dependencies: []

galaxy_info:
  author: Bastien Couder
  description: This ansible role is used to install Nginx Server on linux.
  company: "Bastien Couder"
  license: "license (BSD, MIT)"
  role_name: ansible_role_nginx
  namespace: bastien
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
    - server
    - nginx
    - ubuntu
    - debian
    - centos
    - webserver
