- name: Vérifier si PHP est déjà installé
  stat:
    path: "/usr/bin/php"
  register: php_installed

- name: Ajouter le dépôt PHP si nécessaire
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
  when: 
    - php_specific_version | default(false)
    - not php_installed.stat.exists

- name: Définir les paquets PHP à installer
  set_fact:
    php_packages:
      - git
      - unzip
      - "{{ 'php' + php_version if php_specific_version | default(false) else 'php' }}"
      - "{{ 'php' + php_version + '-fpm' if php_specific_version | default(false) else 'php-fpm' }}"
      - php-mysql
      - php-mbstring
      - php-xml
      - php-curl
      - php-bcmath

- name: Installer les paquets PHP
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: yes
  when: not php_installed.stat.exists