---
- name: Install required packages
  apt:
    pkg:
      - git
      - unzip
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xml
      - php{{ php_version }}-curl
      - php{{ php_version }}-bcmath
    state: present
    update_cache: true

- name: Install Composer
  apt:
    pkg: composer
    state: present
    update_cache: true
