---

- name: Add PHP repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
  when: php_specific_version | default(false)

- name: Install PHP packages
  apt:
    pkg:
      - git
      - unzip
      - "{{ 'php' + php_version if php_specific_version | default(false) else 'php' }}"
      - "{{ 'php' + php_version + '-fpm' if php_specific_version | default(false) else 'php-fpm' }}"
      - php-mysql
      - php-mbstring
      - php-xml
      - php-curl
      - php-bcmath
    state: present