---
name: Release to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Ansible role
        run: |
          pip install ansible-lint
          ansible-lint

      - name: Publish to Galaxy
        uses: robertdebock/galaxy-action@2.0.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
