---
name: SSH Agent Configuration and Remote Command

on: [push , workflow_dispatch]

jobs:
    ssh-job:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4

          - name: Debug
            run: |
              ls -la ~/.ssh
              ssh-keygen -lf ~/.ssh/id_ed25519
              echo "Testing connection..."
              ssh -v -i ~/.ssh/id_ed25519 debian@51.75.18.60 || tru
    
          - name: Setup SSH
            run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan 51.75.18.60 >> ~/.ssh/known_hosts

          - name: Test Connection
            run: ssh -o StrictHostKeyChecking=no debian@51.75.18.60 "echo 'Success!'"